grovesNL/glyphon

- Cargo.toml
- examples/hello-world.rs
- src/lib.rs
- src/recently_used.rs
This allows the glyph cache to be shared between renderers.
Fixes #6
For now, we also reuse some other fields where possible (e.g. params, bind groups). We could change this later if we'd any of these to vary between renderers.
This doesn't change the storage, so a single 2D texture is still used for now.
Some other ideas:
- We could empty the cache easily if we had an `Arc` per glyph to know if it needs to remain in the cache. This would probably be really heavyweight and we'd need to change the refcount per glyph every time `prepare` is called, so I avoided this approach.
- Pass `layouts` into `render` and verify the glyphs  exist instead of storing them in a `Vec` on `TextRenderer`. I didn't do it this way because `layouts` can change between `prepare` and `render`, although maybe we …
> Share atlas between text renderers

- examples/hello-world.rs
- src/lib.rs
Removes the internal `RwLock` in favor of accepting `&mut TextAtlas` (follow-up from https://github.com/grovesNL/glyphon/pull/9#issuecomment-1137501663)
> Accept atlas in `prepare` and `render`

- src/lib.rs
Better support WebGL by padding uniform block to 16-byte alignment, which will usually cause the block size to match `UNIFORM_BLOCK_DATA_SIZE` on WebGL.
We might be able to remove this or handle it differently eventually depending on how it's supported upstream.
(see https://github.com/gfx-rs/wgpu/issues/2072#issuecomment-1147599245 for more context)
> Pad to improve WebGL support

- src/shader.wgsl
This is needed for the new WebGL2 16-byte alignment downlevel check in wgpu 0.13
> Pad `Params` in shader

- examples/hello-world.rs
- src/lib.rs
- src/shader.wgsl
- src/text_atlas.rs
- src/text_render.rs
Alternative fix to #25 that also includes depth-stencil state, so we can fit the pipeline into more existing renderpasses
> Set renderer multisample and depth-stencil state

- examples/hello-world.rs
- src/lib.rs
- src/text_render.rs
This is specially useful if you want to render the same `Buffer` with different default colors.
> Set `default_color` per `TextArea`

- src/text_atlas.rs
- src/text_render.rs
Instead, issue a `write_texture` for every glyph that isn't present in the atlas. I think this should be fine, since cache eviction should be rare and, therefore, uploads will be too.
The result here is lower memory usage for bigger caches.
> Remove potentially huge `texture_pending` from `InnerAtlas`

- examples/hello-world.rs
- src/text_atlas.rs
Noticed colors produced by `swash` are already in the sRGB color space.
> Use `Srgb` texture format for `TextAtlas`

- src/text_render.rs
Not sure if this was for future-proofing the API, but an immutable `render` is necessary to issue multiple out-of-order `render` calls on the same `pass` if you have a collection of `TextRenderer`.
> Make `render` take an immutable `self`

- src/lib.rs
- src/text_atlas.rs
- src/text_render.rs
Prompted by https://github.com/iced-rs/iced/pull/1888.
This PR introduces a `ColorMode` enum that provides indirect control over the gamma correction behavior of the colored glyphs in a `TextAtlas` (like emoji).
I am not sure if this is the best way to expose this functionality, but the way browsers perform color blending is so asinine that I can't really think of a better way. Open to suggestions!
> Introduce `ColorMode` for `Atlas`

- src/lib.rs
This PR just adds a tiny summary of the goal of the crate for the doc.rs page.
> Doc: Add small summary of crate goal in doc.rs

- Cargo.toml
- examples/hello-world.rs
- src/error.rs
- src/lib.rs
- src/text_atlas.rs
- src/text_render.rs
The `TextAtlas` will have an initial size of `256` (we could make this configurable) and `try_allocate` will keep track of the glyphs in use in the current frame, returning `None` when the LRU glyph is in use.
In that case, `TextRenderer::prepare` will return
`PrepareError::AtlasFull` with the `ContentType` of the atlas that is full. The user of the library can then call `TextAtlas::grow` with the provided `ContentType` to obtain a bigger atlas (by `256`).
A `TextAtlas::grow` call clears the whole atlas and, as a result, all of the `prepare` calls need to be repeated in a frame until they all succeed. Overall, the atlas will rarely need to grow and so the calls will not need to be repated often.
Finally, the user needs to call `TextAtlas::trim` at the end of the frame. This allows us to …
> Implement growing logic for `TextAtlas`

- Cargo.toml
- examples/hello-world.rs
- src/lib.rs
- src/text_render.rs
Depends on #31.
The latest `cosmic-text` release performs bucketing calculations after layouting. This allows us to provide proper subpixel offsets, as well as scale any buffer thanks to its linear layout properties.
See https://github.com/pop-os/cosmic-text/pull/143.
Closes #3.
> Subpixel glyph positioning and scaling

- src/error.rs
- src/shader.wgsl
Hi, 
just two simple changes.
Without the interpolation attribute I got errors when compiling the shaders when running in a browser. 
> (User-defined [vertex](https://www.w3.org/TR/WGSL/#vertex) outputs and [fragment](https://www.w3.org/TR/WGSL/#fragment) inputs of scalar or vector integer type [must](https://www.w3.org/TR/WGSL/#shader-creation-error) always be specified as @interpolate(flat).)
from https://www.w3.org/TR/WGSL/#interpolation
I also noticed the missing impl Error with RenderError. If that was intentional feel free to revert.
> Add Interpolation attribute for the VertexOutput and add Error trait implementation for RenderError

- Cargo.toml
This version of `winit` solves a problem related to MacOS Sonoma.
See: https://github.com/rust-windowing/winit/issues/2876
> Bump `winit` to `0.28.7`

- src/text_atlas.rs
- src/text_render.rs
I was fixing up my own project when I noticed there were some clippy warnings about Glyphon. I did not fix the too many arguments issue as not much can be done about that.
> Fixed Clippy and Cargo warnings

- src/lib.rs
Before this commit, all reexported symbols were displayed as if they were part of `glyphon` directly. Users not being able to see at a glance what's part of which crate has a few disadvantages. It makes understanding the whole stack more difficult, since it's unclear what's part of the wgpu-integration and what's part of the general text handling. Personally, I also think this can deter people from using glyphon as this makes the crate (which is "just" the wgpu integration) seem huge. Finally, some symbols in the docs were not linked (as if it was private), which is also really bad for browsing docs.
> Add `#[doc(no_inline)]` to cosmic-text reexports 

- src/text_atlas.rs
This reduces the amount of growing necessary for large glyphs.
> Grow atlas by a factor of `2`

- src/lib.rs
- src/shader.wgsl
- src/text_atlas.rs
- src/text_render.rs
Use the `color_mode` from the atlas to decide whether colors should be converted to linear per vertex.
This should address the review comment at https://github.com/grovesNL/glyphon/pull/75#pullrequestreview-1822316027
I kept the calculation on the GPU for now because it gives us slightly better precision for the linear colors (e.g., for blending), but there's a minor trade-off there.
@hecrj could you check this against your test case (or let me know how to run it)? Thank you!
> Don't convert web text colors to linear

- Cargo.toml
- examples/hello-world.rs
Only thing I had to do was update `request_device` and I wrapped the window in an `Arc` per the new safe surface creation rules.
> update to wgpu 0.19.0

- Cargo.toml
This change will allow people who want to build this crate for web (especially today) to do so, by allowing them to
transitively turn off the default wgpu features.
Turning it back on would be this crate's default feature, so current consumers wouldn't have to change anything, but
people who want web now can now do:
```toml
[dependencies]
glyphon = { version = "0.5.0-whatever", default-features = false }
wgpu = { version = "0.19.1-cool-beans", default-features = false, features = ["webgl"] }
```
> Do a little feature magic to allow to build for web

- Cargo.toml
- examples/hello-world.rs
I needed some features from `cosmic-text` 0.11, so I bumped the version. The API barely changed, so the diff is minor.
> Bump cosmic-text to 0.11

- src/text_render.rs
This avoids constantly reallocating the storage for the vertices and indices uploads.
Basically, it completely removes the initial bump here:
When combined with #90, here's the result:
> Reuse `Vec` allocations in `TextRenderer`

- Cargo.toml
- src/text_atlas.rs
The `HashSet` of `glyphs_in_use` in the text atlas is using the default SipHash 1-3 hasher.
Switching to `ahash`, which is already used by the `LruCache`, increases performance a bit.
This seems to remove the `Hasher::write` calls in my flamegraphs:
vs
> Use `rustc-hash` for `HashSet` of `glyphs_in_use`

- examples/hello-world.rs
- src/lib.rs
- src/text_atlas.rs
- src/text_render.rs
- src/viewport.rs
This PR introduces a `Viewport` type that explicitly holds the `Params` of a `Pipeline`.
This allows sharing a `Viewport` with multiple `TextRenderer` instances, reducing pipeline context changes.
Depends on #95.
> Introduce explicit `Viewport` sharing

- Cargo.toml
- examples/hello-world.rs
This fixes a crash when closing the example window.
(This is a new PR in a different branch because vscode was making a huge mess trying to rebase with merge conflicts.)
> update example to use winit 0.30

- src/text_render.rs
Currently it seems that text is being clipped per glyph and if there are whole lines outside of the visible bounds, it'll still have to go through each glyph on each line. This can be really really slow with super long files
Without the changes in my iced app:
With the changes:
> Only iterate on visible runs within textbounds

- examples/text-sizes.rs
I created an example that displays some example text at various different sizes.
I figured we could also use this to more easily test out various improvements to text rendering quality in the future.
> add text-sizes example

- src/text_render.rs
The method's lifetimes are far too restrictive, which makes the method really annoying to use. I'm not sure if you have any plans to make use of these restrictions in the future, but I don't see why you would need to.
> Relax lifetimes on TextRenderer::render()

- src/text_render.rs
I'm fairly sure this calculation isn't correct (thought I may be wrong). If I recall correctly, the `text_area` bounds are supposed to be in physical pixels, while the `run_line` is in logical pixels.
In a nutshell, my program had problems before this fix, now it doesn't.
> Fix the `is_run_visible` calculation

- examples/custom-glyphs.rs
- examples/hello-world.rs
- examples/text-sizes.rs
Checked to see if I could help out keeping dependencies updated, and found minor compilation warnings in the examples.
Added some minor fixes to resolve those warning ;)
> Applied cargo clippy and minor fixes to examples
